export default QuestionSeeder = [
  {
    question: "How did you work with someone who was difficult to work with?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "What skills do you look for in young hires?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "How do I sell my idea to my boss?", 
    userId: 1 ,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do you work under someone who is not good at communicating?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How long do you recommend staying at your first job? Why?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "I’m having trouble keeping up with all the things at work, what do I do?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "How do I spot opportunities in my career?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How would you earn respect from team members who are more experienced than you?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do I deal with an unreasonable client/ customer?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "I want to set boundaries for my working time to manage stress, but I don’t want to be seen as not pulling my weight. What do I do?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "I am lost on what to do next. Where do I start?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "Different people are saying different things in a project. How do I make sense of everything?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "How do I give feedback to my supervisor?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do you manage disagreements with another person?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "What is a time when you had to solve a problem, but didn’t have all the information beforehand? What did you do?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question:"What is one of the most difficult things you had to learn at work?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do you handle team members who are not cooperative?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "What’s the best advice you’ve received at work?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "What’s your advice to helping my older colleagues be more comfortable with technology?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do you work with someone from a very different field of expertise?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do I know what someone really wants so I can help them?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "Was there a time when you were communicating with someone and they did not understand you? What did you do?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "What do I do if my customer/ client keeps on changing his mind?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do you weigh the pros and cons before making a decision?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "How do you ask for a pay raise?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "What is creative behaviour at work?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do you adjust your working styles to the different people you meet?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "I want to “speak up” during meetings, but I don’t know what to say. What do I say?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { question: "How do you deliver bad news to another person?", 
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "What innovation are you most proud of in your company? What’s the story behind that?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    question: "How do I find & develop relationships with mentors?",
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
